# Generated by Django 3.1.5 on 2021-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
