# Generated by Django 3.1.5 on 2021-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='namek',
            field=models.CharField(default='', max_length=100),
        ),
    ]
